### ISSUE TITLE
How to run this in repl.it or glitch

### ISSUE THREAD

**Issue by thedexterwhiz** [notsapinho/topgg-bot-voter#2]

**Comment by notsapinho** [comment]
It doesn't run on glitch because of headless mode. When in headless mode (background mode) the recaptcha identifies that you are a bot and the captcha appears, but i think it can be bypassed im going to test it out and make and update

**Comment by notsapinho** [comment]
I tested it out and now it can run in headless, just clone it on glitch and it will be working

**Comment by thedexterwhiz** [comment]
Thanks. Pls do it. Your project is great. I really wan't to do it

**Comment by notsapinho** [comment]
so on glitch it's a little buggy, i recommend running on repl.it

**Comment by notsapinho** [comment]
yo bad news, it doesnt work on any free hosting website because of discord captcha when in headless mode

**Comment by thedexterwhiz** [comment]
> yo bad news, it doesnt work on any free hosting website because of discord captcha when in headless mode

Bro [check this out](https://repl.it/talk/share/This-time-we-are-getting-puppeteer/28380)

**Comment by thedexterwhiz** [comment]
const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch({ headless: false, args: ['--no-sandbox', '--disable-setuid-sandbox'] });
  const page = await browser.newPage();

  page.goto("https://repl.it/");
  // More commands here...
  /* You may view the docs at:
       https://devdocs.io/puppeteer/
     And more magic at:
       https://www.npmjs.com/package/puppeteer
     Github:
       https://github.com/puppeteer/puppeteer
  */

  // await browser.close();
})();``
