### ISSUE TITLE
Warning: You can get banned

### ISSUE THREAD

**Issue by Flam3rboy** [notsapinho/topgg-bot-voter#3]
I in fact used this with thousands of accounts also with my main account and my main account got banned for it, because it voted exactly every 12 hours.
Make it so it randomly delays it.

**Comment by notsapinho** [comment]
thanks for the advice, but where did you get banned?

**Comment by notsapinho** [comment]
Added a delay and hope it fixed the problem. Thanks!

**Comment by Flam3rboy** [comment]
I was once even in the top 10 with my 400 guilds bot 😂
